### ISSUE TITLE
`ENOENT: No such file or directory` error during build in docker in github actions

### ISSUE THREAD

**Issue by IslamZaoui** [opral/inlang-paraglide-js#122] opened 2024-05-18 00:55 UTC
Hello, Im currently facing this issue in my sveltekit project

```bash
#17 [frontend 4/6] RUN bun install
#17 0.064 bun install v1.1.8 (89d25807)
#17 0.067  Resolving dependencies
#17 0.110  Resolved, downloaded and extracted [2]
#17 4.296  Saved lockfile
#17 4.296 
#17 4.296 $ paraglide-js compile --project ./project.inlang --outdir ./locales/paraglide
#17 4.534 ℹ [paraglide] Compiling inlang project at "./project.inlang".
#17 4.536 ENOENT: No such file or directory
#17 4.536    errno: -2
#17 4.536  syscall: "stat"
#17 4.536 
#17 4.536 
#17 4.536 Bun v1.1.8 (Linux x64 baseline)
#17 4.539 error: postinstall script from "myblogv2" exited with 1
#17 ERROR: process "/bin/sh -c bun install" did not complete successfully: exit code: 1
```

github [repo](https://github.com/IslamZaoui/MyblogV2) of my project

**Comment by LorisSigrist** [comment] 2024-05-21 14:53
Could you share the dockerfile you used for this? I can't reproduce this at the moment

**Comment by IslamZaoui** [comment] 2024-05-22 09:08
I delete the code from my repo
but here is what I wrote in that docker file:
```dockerfile
FROM alpine:latest as downloader
ARG VERSION=0.19.4
ARG ARCH=linux_amd64
RUN wget https://github.com/pocketbase/pocketbase/releases/download/v${VERSION}/pocketbase_${VERSION}_${ARCH}.zip \
    && unzip pocketbase_${VERSION}_${ARCH}.zip -d /tmp/ \
    && chmod +x /tmp/pocketbase

FROM alpine:latest as base
WORKDIR /app
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=downloader /tmp/pocketbase /app/pocketbase
EXPOSE 8090
CMD ["./pocketbase", "serve", "--http=0.0.0.0:8090"]

FROM oven/bun:1.0 as frontend
WORKDIR /app
COPY ./ ./
RUN bun install
RUN bun run build

FROM base as prod
COPY ./pocketbase/pb_hooks /app/pb_hooks
COPY ./pocketbase/pb_migrations /app/pb_migrations
COPY --from=frontend /app/build /app/pb_public
```
The error occurs after install

**Comment by LorisSigrist** [comment] 2024-06-10 06:53
Everyone seems to be using `bun` which also doesn't run properly outside of a docker file. Does the issue still occur if you use `node`?

**Comment by janfjohannes** [comment] 2024-06-11 15:58
@dihmeetree  can you try without the --link ?

**Comment by LorisSigrist** [comment] 2024-06-11 15:59
I can only reproduce this when using `bun` in order to install or build. The following docker file using `node` directly works as expected with a SvelteKit project.

```dockerfile
# Use the official Node.js image as a base image
FROM node:18

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

CMD ["npm", "run", "preview"]
```

**Comment by TheKinng96** [comment] 2024-08-13 06:17
try the dockerfile below
add `CMD` if needed, I am having the command on docker-compose so not going to have the `CMD` in dockerfile

this is the workaround because paraglide js needs some APIs that bun doesnt provide and alpine image has other missing libraries that bun package needs, so ended up having the full size node image to install bun and use bun

```
# Step 1: Use an official Node.js image as the base image
FROM node:22 AS builder

# Install Bun
RUN npm install -g bun

# Set the working directory in the container
WORKDIR /app

# Copy package.json and bun.lockb files
COPY package.json bun.lockb ./

# Install project dependencies using Bun
RUN npx bun install

# Copy the rest of the application source code
COPY . .

# Expose the port the application will run on
EXPOSE 8080

```

**Comment by karisDev** [comment] 2024-08-27 08:56
did anyone manage to fix it using bun?

**Comment by TheKinng96** [comment] 2024-08-27 09:59
> did anyone manage to fix it using bun?

I have my dockerfile working, see above

The bun official image doesn't have some node API that paraglide needs, a workaround is to use node image and install bun then use bun as worker

**Comment by samuelstroschein** [comment] 2024-09-03 04:19
Hey everyone, I am taking over Paraglide JS again this week. I am closing this issue as the 2.0 release is the top prio atm [https://github.com/opral/inlang-paraglide-js/issues/201](https://github.com/opral/inlang-paraglide-js/issues/201)

**Closed by samuelstroschein** 2024-09-03 04:19 UTC
Labels: bug
