### ISSUE TITLE
SvelteKit load functions doesn't always re-run

### ISSUE THREAD

**Issue by oskarrough** [opral/inlang-paraglide-js#247] opened 2024-10-18 11:26 UTC
The last days I've been trying to setup the paraglide sveltekit plugin together with a fresh Svelte 5 project.

The inlang messaging APIs work great.

What doesn't work is the logic to re-run or trigger the `load()` functions of SvelteKit routes, when language is changed. Paraglide svelte runs `invalidate('paraglide_lang')`, which triggers any load function that contains `depends('paraglide_lang'). So far so good, except it doesn't always work.

1. Say we have two languages: da for Danish and en for English.
2. You navigate to /da/page
3. Click a link to the english version /en/page, load function is not re-run unless you manually call invalidate/reload

I found two workarounds to trigger the load functions

1. Manually running `invalidateAll` or `invalidate('paraglide_lang')`

```js
import { goto, invalidateAll } from '$app/navigation'
import { page } from '$app/stores'
import { get } from 'svelte/store'

/** @param { import("$lib/paraglide/runtime").AvailableLanguageTag } newLanguage */
async function switchToLanguage(newLanguage) {
	const canonicalPath = i18n.route(get(page).url.pathname)
	const localisedPath = i18n.resolveRoute(canonicalPath, newLanguage)
	await goto(localisedPath, {invalidateAll: true}) // <-- this here
}
```

2. Forcing reloads on links using "data-sveltekit-reload" attribute:

```html
<a
	data-sveltekit-reload
	href="/about"
	hreflang="da"
	aria-current={languageTag() === 'da' ? 'page' : false}>Dansk</a
>
```

But isn't the paraglide sveltekit plugin supposed to do this for you? Maybe the logic here needs a refactor https://github.com/opral/monorepo/blob/bebae597477d11cef27c7a03fbf41105ba736d01/inlang/source-code/paraglide/paraglide-sveltekit/src/runtime/ParaglideJS.svelte#L46-L48.

Here's a clean repo reproduction that shows all this https://github.com/oskarrough/paraglide-sveltekit-test.

**Comment by samuelstroschein** [comment] 2024-10-18 11:35
Oskar, 

First, thanks for the elaborate issue and reproduction (!). 

I am happy to review and accept a PR to fix the re-run of load functions. I don't have time atm to look into this myself ([see focus on lix 1.0](https://opral.substack.com/p/focus-shift-from-inlang-to-lix)). The tricky part is only reloading the load function if a language changes.

Three options: 

1. Use the workaround and ignore the problem until after https://github.com/opral/inlang-paraglide-js/issues/217
2. Open a PR to update the language switcher example to use `invalidateAll: true`
3. (Not recommended) Open a PR to add language switching detection to the compiler and add `data-sveltekit-reload` to the `<a>` where needed

**Comment by twoends** [comment] 2024-11-03 12:01
I'll add a couple notes here as a confirmation that a bug actually exists.
First of all, the documentation is misleading. On the website you can read

> If you have a load function that returns data that depends on the language you can tell it to re-run on language changes by calling depends("paraglide:lang").

while the correct label appears to be `depends("paraglide_lang")`. Also, `paraglide_lang` seems not to fit the Sveltekit [documentation](https://svelte.dev/docs/kit/$app-navigation#invalidate): 

> use a string beginning with [a-z]+: (e.g. custom:state)

Now, this is what I debugged so far:
I have a server-side fetch request that depends on the current language. Without `depends("paraglide_lang")` the request is never re-executed on language change, so I added the `depends("paraglide_lang")` in the load function. If I start the page with the `it` locale, the fetch request get executed as expected. When I switch from `it` to `en` (with a link according to the paraglide-sveltekit documentation) the fetch request **DOES NOT** gets executed again. If I switch again to `it` the fetch request gets executed again.

**Comment by twoends** [comment] 2024-11-03 12:15
I just tried the 0.11.5 version and the issue seems to be resolved.

**Comment by samuelstroschein** [comment] 2024-11-03 14:32
Closing this issue as completed in 0.11.5 as per @twoends comment. Re-open if the issue still persists.

**Closed by samuelstroschein** 2024-11-03 14:32 UTC
