### ISSUE TITLE
Paraglide-next 0.7.2 in Next. Nextjs v15 the page is not change immediately

### ISSUE THREAD

**Issue by alialnaghmoush** [opral/inlang-paraglide-js#255] opened 2024-11-07 15:48 UTC
I Build Next.js v15 start kit with ShadCN + Drizzle + Paraglide-Next + Next-Themes...

All package work right, but Paraglide-Next has bug it's not work properly
I use it next.js v14 Paraglide-Next v0.6 it's work fine

When I click to switch the language in the URL is changed and cookies, but the page not refresh to presents right language, please fix the bug as soon as possible
![Screen Recording Nov 7 2024](https://github.com/user-attachments/assets/924faa7c-f3c4-446f-8e40-98a5fa116c85)

**Comment by mateuszaliyev** [comment] 2024-11-08 07:48
I am also facing this issue in my other projects, so I made a [minimal reproduction](https://github.com/mateuszaliyev/paraglide-next-15). `@inlang/paraglide-next@0.6.0` does not seem to have this bug with `next@^15` (other than warnings about not `await`ing `headers`).

**Comment by dilincoln** [comment] 2024-11-16 03:40
Currently(0.7.2), I'm running `revalidatePath("/", "layout")` then `window.location.reload()`.

Running any of them alone, doesn't work.

**Comment by stylehuan** [comment] 2024-11-18 08:48
same problem（0.7.2)

**Comment by MarcusAndreasSvensson** [comment] 2024-11-18 20:42
I am running next@^14.2.15 and am also having this issue on both 0.7.0, 0.7.1 and 0.7.2.

I do not have the same issue when downgrading to 0.6.0

**Comment by stylehuan** [comment] 2024-11-26 08:40
Excuse me, is there any progress on this

**Comment by giray123** [comment] 2024-12-13 16:24
Having the same problem, it is very unstable(0.7.4) with next 15.

**Comment by ThibaultWalterspieler** [comment] 2024-12-17 16:15
Same problem her. 
I really need a fix on this, otherwise I'll have to turn to a new product. 

I'm on `next@15.0.4` and `@inlang/paraglide-next@0.7.4`

**Comment by samuelstroschein** [comment] 2024-12-19 15:28
Somehow, I did not get a notification for this issue. 

I have a suspicion about what it likely is. I will try to squeeze fixing the bug into my work day. https://discord.com/channels/897438559458430986/1319288922483724348/1319311255454093342

**Comment by samuelstroschein** [comment] 2024-12-19 22:15
NextJS is rendering the HTML on the server before awaiting the language from the headers. Investigation pending 

![CleanShot 2024-12-19 at 16 56 55@2x](https://github.com/user-attachments/assets/c6449db3-8f89-4bf6-8bc0-69b8a14eb7bb)

**Comment by samuelstroschein** [comment] 2024-12-19 23:17
The bug is caused by NextJS. Awaiting the headers does not suspend rendering. Here is an in-depth video on how to reproduce the issue https://www.loom.com/share/5aacf7e9c7e14e0cae841df41b816c2a

**Two options**

1. Someone makes a PR that finds a solution or another implementation like using AsyncLocalStorage 
2. Switch to [next-intl](https://next-intl.dev/), which does not seem to have an issue with NextJS 15. An [inlang plugin for next-intl](https://inlang.com/m/193hsyds/plugin-inlang-nextIntl) exists. 

_I am unable to spend more time on this issue. If someone wants to become the maintainer of the NextJS adapter, please reach out. I am unable to provide full support for the NextJS adapter. NextJS has too many quirks and custom solutions (edge runtime, RSC, turbopack, etc.)_

**Comment by samuelstroschein** [comment] 2024-12-21 20:41
Fixed in `0.7.5` by making the headers sync again. 

The warning in the console that headers should be awaited disappears in production. See https://github.com/opral/inlang-paraglide-js/issues/245.

**Closed by samuelstroschein** 2024-12-21 20:41 UTC
