### ISSUE TITLE
Error: Route "/" used `headers().get('x-language-tag')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

### ISSUE THREAD

**Issue by diegosilva91** [opral/inlang-paraglide-js#277] opened 2024-12-19 01:15 UTC
✓ Compiled / in 48ms
Error: Route "/" used `headers().get('x-language-tag')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at <unknown> (paraglide/runtime.js:77:20)
    at RootLayout (app/layout.tsx:50:30)
  75 | function enforceLanguageTag(unsafeLanguageTag) {
  76 |     return () => {
> 77 |         const tag = unsafeLanguageTag()
     |                    ^
  78 |         if(!isAvailableLanguageTag(tag)) {
  79 |             throw new Error(`languageTag() didn't return a valid language tag. Check your setLanguageTag call`)
  80 |         }

**Comment by samuelstroschein** [comment] 2024-12-19 14:40
duplicate of [https://github.com/opral/inlang-paraglide-js/issues/267](https://github.com/opral/inlang-paraglide-js/issues/267). comment in the other issue if paraglide-next ^0.7.1 fixes this issue

**Closed by samuelstroschein** 2024-12-19 14:40 UTC
