### ISSUE TITLE
How to Import a Module Globally in SvelteKit

### ISSUE THREAD

**Issue by kenzWeb** [opral/inlang-paraglide-js#239] opened 2024-10-10 21:32 UTC
Hello,

I'm working on a SvelteKit project and using a module frequently across multiple files, specifically `messages.js` from `$lib/paraglide`. Currently, I have to import it manually in each file like this:

```javascript
import * as m from '$lib/paraglide/messages.js';
```

Is there a way to make this module available globally throughout the project, so I don't have to import it every time?

Any advice or recommended best practices would be greatly appreciated.

Thank you!

**Comment by samuelstroschein** [comment] 2024-10-11 16:14
hi @kenzWeb, 

i am unaware of a possibility to make modules global without breaking tree-shaking. 

i also advice you against globals. the imports might be annoying but it works. global magic will likely introduce regressions bugs. 

in terms of achieving global modules, check the vite docs [https://vitest.dev/](https://vitest.dev/). paraglide js emits regular javascript code. 

---

*closing because not directly related to paraglide js*

**Closed by samuelstroschein** 2024-10-11 16:14 UTC
