### ISSUE TITLE
sveltekit plugin is broken since vite@5.2.0-beta.1

### ISSUE THREAD

**Issue by ZerdoX-x** [opral/inlang-paraglide-js#41] opened 2024-03-23 15:03 UTC
Original issue (since it was not intended to be a breaking change from vite side) was opened here: https://github.com/vitejs/vite/issues/16245

I have created the issue here, in case it can be solved on paraglide side, and so people could know if they stumble upon this, the current solution is to downgrade to vite@5.2.0-beta.0 or vite@5.1.6

UPD: I have tried to reproduce the issue without sveltekit, no luck

**Comment by arxpoetica** [comment] 2024-03-23 16:07
I came here to post the same thing. Here's a reproduction of the bug, pre-and-post v5.1.6 Vite:

https://github.com/arxpoetica/inlang-sveltekit-vite-bug

**Comment by LorisSigrist** [comment] 2024-03-25 08:06
Thanks for the repro, that's always really helpful!

**Comment by LorisSigrist** [comment] 2024-03-25 12:54
Seems like this bug was caused by a downstream issue in one of our our dependencies. Will be fixed in the next release

**Closed** 2024-03-25 13:06 UTC

**Comment by LorisSigrist** [comment] 2024-03-25 15:58
There \_was\_ a legitimate issue in paraglide, it just happened to be surfaced by a bug in vite. Either being fixed solves the issue. Great to see that the vite bug was fixed!  

Thanks for the through issue + follow up!
