### ISSUE TITLE
No warnings/indications for missing message source for `message-lint-rule-without-source` plugin

### ISSUE THREAD

**Issue by SaintPepsi** [opral/inlang-paraglide-js#226] opened 2024-09-22 11:55 UTC
I added the "Missing translation" [Message Lint Rule](https://inlang.com/m/4cxm3eqi/messageLintRule-inlang-missingTranslation) to my Sveltekit project's `project.inlang/settings.json` file:

```json
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": ["en", "nl", "fil"],
	"modules": [
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-valid-js-identifier@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js"
	],
	"plugin.inlang.messageFormat": {
		"pathPattern": "./messages/{languageTag}.json"
	},
	"messageLintRuleLevels": {
		"messageLintRule.inlang.messageWithoutSource": "error",
		"messageLintRule.inlang.validJsIdentifier": "error"
	}
}
```

But in fink it only shows "Identical pattern"

<img width="1208" alt="image" src="https://github.com/user-attachments/assets/f781a31f-b06d-4258-af2b-18f45dc1eb30">

When I search for a specific translation key that I know is no longer used the messages show up:

<img width="442" alt="image" src="https://github.com/user-attachments/assets/2c4c4c98-8f81-4d48-b6a6-8c55f27a6a55">

How does one check for translations that are no longer used in your application?

**Comment by samuelstroschein** [comment] 2024-09-22 21:18
Hi @SaintPepsi, 

> How does one check for translations that are no longer used in your application?

See this issue https://github.com/opral/inlang-sdk/issues/6#issue-2201429189. 

In regards to the missing translation rule that you used, it checks if a translation is missing. Not if a message is used in code. Closing this as a duplicate of https://github.com/opral/inlang-sdk/issues/6.

**Closed by samuelstroschein** 2024-09-22 21:18 UTC
