### ISSUE TITLE
Prevent page from reloading

### ISSUE THREAD

**Issue by kevinschaerer** [opral/inlang-paraglide-js#278] opened 2024-12-20 14:27 UTC
I’m currently using Paraglide.js in a Next.js project with the App Router. When I change the language (via the locale parameter), the URL updates as expected, but the entire page reloads. This behavior interrupts one of my animations.

Is there a way to prevent the full page reload when switching languages, so that only the relevant content updates dynamically while the page remains intact?

**Comment by samuelstroschein** [comment] 2024-12-20 15:55
No. The trade-off to re-load the page is on purpose. A user only switches the language once when the initial language was wrong. 

Making a reload when switching the language leads to 

* small runtime, faster page loads, better SEO 
* severely simpler runtime implementation, keeping paraglide js simple

Is your app a website or app? Website = content stuff where SEO is important. App = Dynamic interactions, bundle size and SEO not important

**Comment by samuelstroschein** [comment] 2024-12-23 11:04
Closing this as intended to keep bundle sizes small and Paraglide simple to maintain.

**Closed by samuelstroschein** 2024-12-23 11:04 UTC
